// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'marche_social_webapp';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String MOCKUP_1 = 'assets/images/mockup-1.png';
  static const String MOCKUP_2 = 'assets/images/mockup-2.png';
  static const String MOCKUP_3 = 'assets/images/mockup-3.png';
  static const String MOCKUP = 'assets/images/mockup.png';
}
