// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBStyCnI1SoF5FxXWyGRAIVaNpg6JjxCSU',
    appId: '1:490717525694:web:4e795dfb96af87bbd010ef',
    messagingSenderId: '490717525694',
    projectId: 'marche-social',
    authDomain: 'marche-social.firebaseapp.com',
    storageBucket: 'marche-social.appspot.com',
    measurementId: 'G-REVM5HZQR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCav0f9t36DzdnisV9FwHIOlgk3qw3LF9I',
    appId: '1:490717525694:android:e42937978572f1b8d010ef',
    messagingSenderId: '490717525694',
    projectId: 'marche-social',
    storageBucket: 'marche-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6EXOyZVoZ48zgh3eWHfrIH4iuOyFl7pk',
    appId: '1:490717525694:ios:0773199b19d2f9afd010ef',
    messagingSenderId: '490717525694',
    projectId: 'marche-social',
    storageBucket: 'marche-social.appspot.com',
    androidClientId: '490717525694-kn5c20t2asva5a7ljiua8b5igqt7gagk.apps.googleusercontent.com',
    iosClientId: '490717525694-air9487qmhgjjnn4ppn0jec2b1iaih9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.marcheSocialWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6EXOyZVoZ48zgh3eWHfrIH4iuOyFl7pk',
    appId: '1:490717525694:ios:0773199b19d2f9afd010ef',
    messagingSenderId: '490717525694',
    projectId: 'marche-social',
    storageBucket: 'marche-social.appspot.com',
    androidClientId: '490717525694-kn5c20t2asva5a7ljiua8b5igqt7gagk.apps.googleusercontent.com',
    iosClientId: '490717525694-air9487qmhgjjnn4ppn0jec2b1iaih9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.marcheSocialWebapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4-yqt9hq0cc4Ng1NvnqIqxxR9dbKG0F8',
    appId: '1:490717525694:web:2655568772d4d7f2d010ef',
    messagingSenderId: '490717525694',
    projectId: 'marche-social',
    authDomain: 'marche-social.firebaseapp.com',
    storageBucket: 'marche-social.appspot.com',
    measurementId: 'G-YVG2RRK1D1',
  );
}
